var inc_dico=0;
var interval_dico=null;
var dictionnaire=null;
var dictionnaire_dur =null;
var db;
var check_inc =null;
var interval_checkdb =null;
var nb_essai_partie_normale = 6;
var nb_essai_super_partie = 2;
var nb_essai = nb_essai_partie_normale;
var last_insert = false;
var toFind ="";
var tryWord="";
var goodKey = new Array();
var nb_reussite_total=0;
var nb_reussite=0;
var nb_game=0;
var declenchement_super_parti = 10;
var letter_checked=new Array();
var real ={"width":0,"height":0};
var lengthWord=-1;
var version="2.0.0";
var is_mobile=false;

var C=2;
var L=1;

var beepCheck;
var beepError;
var beepGood;
var beepNotHere;
var clap;
var boo;
var gasp;